global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "dapr"
    scrape_interval: 5s

    static_configs:
      - targets:
          [
            "host.docker.internal:4200",
            "host.docker.internal:4201",
            "host.docker.internal:4202",
          ]