name: publish to nuget
on:
  push:
    branches:
      - master # Default release branch, may also be named 'master' or 'develop'
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: 3.1.200

      - name: Run
        run : |
            dotnet build "framework/src/BBT.Prism.Core/BBT.Prism.Core.csproj" -c Release
            dotnet pack "framework/src/BBT.Prism.Uow/BBT.Prism.Uow.csproj" -c Release --no-build --output
            ls -l
            dotnet nuget push /app/build/BBT.Prism.Uow*.nupkg --source https://api.nuget.org/v3/index.json --api-key "API-KEY"

