# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore "framework/src/BBT.Prism.Core/BBT.Prism.Core.csproj"
    - name: Build
      run: dotnet build "framework/src/BBT.Prism.Core/BBT.Prism.Core.csproj" --no-restore
    - name: NuGet Publisher
      uses: Jacup/publish-nuget@v2.6.0
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: framework/src/BBT.Prism.Uow 
        NUGET_SOURCE: https://api.nuget.org/v3/index.json
          
          
