# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Create Folder
      run: mkdir -p app/build
    - name: Restore dependencies
      run: dotnet restore "framework/src/BBT.Prism.Uow/BBT.Prism.Uow.csproj"
    - name: Build
      run: dotnet build "framework/src/BBT.Prism.Core/BBT.Prism.Core.csproj" -o app/build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
