# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Create Folder
      run: mkdir -p packages
    - name: Restore dependencies
      run: |
        for path in $(ls framework/src)
        do
          echo $path
          dotnet restore "framework/src/$path"
        done
    - name: Build
      run: |
        for path in $(ls framework/src)
        do
          echo $path
          dotnet build "framework/src/$path" --no-restore
        done
    - name: pack
      run: |
        Version=$(cat common.props | grep -oP '(?<=<Version>).*?(?=</Version>)') 
        for path in $(ls framework/src)
        do
          echo $path
          dotnet pack "framework/src/$path" /p:Version=$Version --output packages/
        done
    - name: publish
      run: |
        for path in $(ls framework/src)
        do
          echo $path
          # dotnet nuget push packages/$path*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.api_key }}
        done
